services:
  web:
    build: ./contacts-app
    image: jessetpats/contacts-app-server
    ports:
      - 5173:5173
  server:
    build: ./express-server
    image: jessetpats/contacts-app-web
    ports:
      - 3000:3000