/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddContactImport } from './routes/addContact'
import { Route as ContactIdImport } from './routes/$contactId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AddContactRoute = AddContactImport.update({
  path: '/addContact',
  getParentRoute: () => rootRoute,
} as any)

const ContactIdRoute = ContactIdImport.update({
  path: '/$contactId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$contactId': {
      id: '/$contactId'
      path: '/$contactId'
      fullPath: '/$contactId'
      preLoaderRoute: typeof ContactIdImport
      parentRoute: typeof rootRoute
    }
    '/addContact': {
      id: '/addContact'
      path: '/addContact'
      fullPath: '/addContact'
      preLoaderRoute: typeof AddContactImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$contactId': typeof ContactIdRoute
  '/addContact': typeof AddContactRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$contactId': typeof ContactIdRoute
  '/addContact': typeof AddContactRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$contactId': typeof ContactIdRoute
  '/addContact': typeof AddContactRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$contactId' | '/addContact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$contactId' | '/addContact'
  id: '__root__' | '/' | '/$contactId' | '/addContact'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIdRoute: typeof ContactIdRoute
  AddContactRoute: typeof AddContactRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIdRoute: ContactIdRoute,
  AddContactRoute: AddContactRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$contactId",
        "/addContact"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$contactId": {
      "filePath": "$contactId.tsx"
    },
    "/addContact": {
      "filePath": "addContact.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
